[15.0][MIG] analytic_plan
Eficent/eficent-odoo-addons pull request #273
Opened 2023-02-22 10:20 UTC by JasminSForgeFlow

2023-02-22 15:03 UTC, AaronHForgeFlow requested changes
Works well so far, just an issue when clicking on this button:
![image](https://user-images.githubusercontent.com/19620251/220661927-0b375e18-cb20-4583-b387-cef67b9625ad.png)


`RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1330, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1318, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/analytic_plan/models/account_analytic_account.py", line 83, in open_plan_cost_tree_view
    line_ids = plan_obj.search(
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 1810, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4714, in _search
    query = self._where_calc(args)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4470, in _where_calc
    return expression.expression(domain, self).query
  File "/opt/odoo/custom/src/odoo/odoo/osv/expression.py", line 442, in __init__
    self.parse()
  File "/opt/odoo/custom/src/odoo/odoo/osv/expression.py", line 898, in parse
    expr, params = self.__leaf_to_sql(leaf, model, alias)
  File "/opt/odoo/custom/src/odoo/odoo/osv/expression.py", line 1035, in __leaf_to_sql
    raise ValueError("Invalid domain term %r" % (leaf,))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid domain term ('account_id', 'in', dict_keys([17]))
`

2023-02-22 15:06 UTC, AaronHForgeFlow commented
@JasminSForgeFlow , I am afraid same issue is happening in v14.0, I merged it too soon. Can you fix that in separate PR?

2023-02-24 04:37 UTC, JasminSForgeFlow commented
> @JasminSForgeFlow , I am afraid same issue is happening in v14.0, I merged it too soon. Can you fix that in separate PR?

Fixed for both, Thanks

2023-03-07 15:25 UTC, AaronHForgeFlow approved these changes

2023-03-07 15:25 UTC, merged