[14.0][mig]-analytic_resource_plan
Eficent/eficent-odoo-addons pull request #298
Opened 2023-03-07 17:35 UTC by JuanyDForgeflow

2023-04-17 11:32 UTC, AaronHForgeFlow commented
Hi @JuanyDForgeflow is this one blocked for some reason?

2023-04-17 15:05 UTC, JuanyDForgeflow commented
@AaronHForgeFlow no, I'll be fixing this

2023-04-19 11:54 UTC, AaronHForgeFlow requested changes
Can you fix resource plan line tree view?

![2023-04-19_13-53](https://user-images.githubusercontent.com/19620251/233066999-ca5ff893-00dd-4199-a20d-d28905447a17.png)

2023-04-19 12:54 UTC, AaronHForgeFlow commented on analytic_resource_plan/wizard/resource_plan_line_change_state_view.xml
> +        model="ir.actions.act_window"
This action is not showing when selecting the resource plan lines in a list view and clicking on More > Action Can you check?

2023-04-19 19:31 UTC, JuanyDForgeflow commented on analytic_resource_plan/wizard/resource_plan_line_change_state_view.xml
> +        model="ir.actions.act_window"
@AaronHForgeFlow I forgot to add it to the security file, it should be working now

2023-04-19 19:31 UTC, JuanyDForgeflow commented
> Can you fix resource plan line tree view?
> 
> ![2023-04-19_13-53](https://user-images.githubusercontent.com/19620251/233066999-ca5ff893-00dd-4199-a20d-d28905447a17.png)

This is fixed now

2023-04-20 15:45 UTC, AaronHForgeFlow commented on analytic_resource_plan/wizard/analytic_resource_plan_copy_version_view.xml
> +                version="7.0"
I don't think this is necessary

2023-04-20 15:45 UTC, AaronHForgeFlow commented on analytic_resource_plan/wizard/resource_plan_line_change_state_view.xml
> +        model="ir.actions.act_window"
That's good, but the actions are still not showing to me. Are they showing to you? They should show in the resource plan line list.

2023-06-06 09:09 UTC, closed without merging