[10.0] [ADD] hr_timesheet_sheet_validators
Eficent/eficent-odoo-addons pull request #46
Opened 2017-08-09 10:57 UTC by nikul-serpentcs

HR Timesheet Sheet Validators
=============================

This module allows a user outside of the Human Resources groups to validate
timesheets. A rule is predefined, but it is flexible enough to accept
extensions.

Timesheets in Odoo can be validated by users belonging to the group
“Human Resources / Officer”. However, it is frequent for companies allow to
employees outside of the Human Resources group to validate time sheet.

At the time when a user submits a time sheet to the Manager, the application
determines the validators.

Only those validators or employees in the group of Human Resources Officer
are capable of approving the timesheet.

The current rule sets as validators of a time sheet:

* The head of the department that the employee belongs to

- In case that the employee is head of the department, it will attempt to add
  the head of the parent department instead.

* The employee’s direct manager

The list of validators is visible in the employee’s timesheet.

2017-08-09 10:57 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-08-09 14:29 UTC, AaronHForgeFlow requested changes
Only code review

2017-08-09 14:29 UTC, aheficent commented on hr_timesheet_sheet_validators/security/hr_timesheet_sheet_security.xml
> +        <!-- <record id="hr_timesheet.property_rule_timesheet_employee" model="ir.rule">
why this is commented?

2017-08-09 14:29 UTC, aheficent commented on hr_timesheet_sheet_validators/tests/test_hr_timesheet_sheet_validators.py
> +                         self.timesheet_sheet.employee_id.parent_id.user_id)
can you extend the test by validating a timesheet?

2017-08-17 07:23 UTC, LoisRForgeFlow requested changes

2017-08-17 07:23 UTC, lreficent commented on hr_timesheet_sheet_validators/__manifest__.py
> +    'author': 'Eficent, Serpent Consulting Services Pvt. Ltd.',
As I said to you in a module yesterday and I am seeing that you doing some more... if you are not adding capabilities, migrations doesn't grant authorship.

2017-08-17 07:34 UTC, nikul-serpentcs commented on hr_timesheet_sheet_validators/__manifest__.py
> +    'author': 'Eficent, Serpent Consulting Services Pvt. Ltd.',
@lreficent please could check it.

2017-10-10 08:55 UTC, AaronHForgeFlow approved these changes
:+1: Thanks for attending the review

2017-10-18 15:52 UTC, aheficent commented
@lreficent I think your comments have been attended

2017-10-19 16:03 UTC, LoisRForgeFlow approved these changes
Yes, ready to merge I think :smile:

2017-10-19 16:05 UTC, merged