[10.0] [ADD] product_manufacturer_add_supplierinfo
Eficent/eficent-odoo-addons pull request #47
Opened 2017-08-11 10:03 UTC by nikul-serpentcs

Product manufacturer add supplier info
======================================

Extended product template. This module allows to automatically create a product
supplier from the product manufacturer information.

2017-08-11 10:04 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-09-28 15:39 UTC, AaronHForgeFlow requested changes
Functional ok

2017-09-28 15:39 UTC, aheficent commented on product_manufacturer_add_supplierinfo/__init__.py
> +# Copyright 2017 Serpent Consulting Services Pvt. Ltd.
Please reserve this for authors. Contributors who migrate can go in the contributors section in the readme.

2017-09-29 13:35 UTC, aheficent commented
I'll merge and do the thing.

2017-09-29 13:35 UTC, merged