[10.0] [ADD] analytic_schedule
Eficent/eficent-odoo-addons pull request #50
Opened 2017-09-07 10:15 UTC by nikul-serpentcs

Analytic Schedule
=================

The project / analytic account's start and end dates are automatically computed based on the earliest start and latest finish date of the children.

2017-09-08 09:06 UTC, AaronHForgeFlow requested changes
Tested as follows:
Created a parent project without dates. Create a child. Add the dates to the child. The dates of the parent remained blank.

2017-09-11 05:29 UTC, nikul-serpentcs commented
@aheficent Added a unit test case, Could you please review.

2017-09-18 07:47 UTC, AaronHForgeFlow requested changes

2017-09-18 07:47 UTC, aheficent commented on analytic_schedule/tests/test_account_analytic_account.py
> +        })
The date should be here, not in the son. Then, when creating the son don't assign any date as the system is supposed to do so.

Regards

2017-09-18 11:21 UTC, nikul-serpentcs commented
@aheficent Created another child with different dates, Could you please look it.

2017-09-20 15:13 UTC, aheficent commented
As in v10 the dates are hold in the project. This module has to be refactored to work with projects instead. As the module name should change I'll close this PR and I'll do the thing in another PR.

2017-09-21 09:15 UTC, aheficent commented
@nikul-serpentcs as we have now in v10 the dates in the project when changing the date of the analytic account we should change also the project that has that analytic_account_id associated. Can you do that?

2017-09-22 10:05 UTC, nikul-serpentcs commented
@aheficent Could you please look it.

2017-09-27 10:16 UTC, AaronHForgeFlow requested changes
Can you also change the analytic dates when the project dates change?

2017-09-28 06:03 UTC, nikul-serpentcs commented
@aheficent Could you please look it.

2017-09-28 07:46 UTC, AaronHForgeFlow requested changes
It is not working. When changing the project dates, the analytic dates are modified, so it will trigger set back the analytic dates to the project.

2017-09-28 07:49 UTC, aheficent commented
This module should be deprecated in v10. It's complex to maintain and does not add any feature. Closed PR. I'm sorry for this.

2017-09-28 07:49 UTC, closed without merging