[10.0] [ADD] stock_analytic_change_product_qty
Eficent/eficent-odoo-addons pull request #58
Opened 2017-09-15 11:24 UTC by nikul-serpentcs

Stock Analytic
==============

 When updating the product qty referring to an analytic account the location must contain the same analytic account

2017-09-15 11:24 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-09-18 15:14 UTC, AaronHForgeFlow reviewed
Functional ok, only some style issues. Besides, I'm not sure if the commit history is respected here

2017-09-18 15:14 UTC, aheficent commented on stock_location_analytic_change_product_qty/README.rst
> +Stock Analytic
Please change this by the correct title

2017-09-18 15:14 UTC, aheficent commented on stock_location_analytic_change_product_qty/__init__.py
> +# Copyright 2017 Serpent Consulting Services Pvt. Ltd.
Reserved for authors of people who introduce important new features

2017-09-18 15:16 UTC, aheficent commented on stock_location_analytic_change_product_qty/README.rst
> +Update the product qty as always
Below add
* Aaron Henriquez <ahenriquez@eficent.com> and yourself as contributors

2017-09-19 06:05 UTC, nikul-serpentcs commented
@aheficent Could you please look it.

2017-09-19 06:17 UTC, nikul-serpentcs commented
@aheficent Could you please look it.

2017-09-20 14:18 UTC, AaronHForgeFlow requested changes
In the wizard I cannot select a location out of the company. We should be able to select also "customer" locations that are associated to an analytic account. Why? Because I don't those products to count as an asset in my warehouse, but the products are already there, and they are assigned to a project. The stock_analytic_location module allows me to do that

2017-09-25 11:45 UTC, nikul-serpentcs commented
@aheficent Could you please look it.

2017-09-26 08:21 UTC, AaronHForgeFlow approved these changes
:+1:  Thanks for attending the review. Can you please squash you commit in just one?

2017-09-26 10:27 UTC, nikul-serpentcs commented
@aheficent squashed commit, Could you please look it.

2017-09-26 10:31 UTC, aheficent commented on stock_location_analytic_change_product_qty/__manifest__.py
> +    'website': 'http://www.eficent.com',
Can you add the license key here? 

Sorry i did not see that before

2017-09-26 11:39 UTC, nikul-serpentcs commented
@aheficent Could you please look it.

2017-09-26 11:48 UTC, AaronHForgeFlow approved these changes
:+1:

2017-09-26 11:52 UTC, merged