[10.0] [ADD] account_analytic_post_by_type
Eficent/eficent-odoo-addons pull request #59
Opened 2017-09-16 07:13 UTC by nikul-serpentcs

Account analytic Post
=====================

This module introduces the following features:

* When validating a journal entry checks that the account type is a Profit & loss account, in case that there's an analytic account associated

2017-09-16 07:17 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-09-26 07:48 UTC, AaronHForgeFlow requested changes

2017-09-26 07:48 UTC, aheficent commented on account_analytic_post_by_type/tests/test_account_analytic_post.py
> +                                                            'Expense'])])
Expenses instead of Expense

2017-09-26 07:48 UTC, aheficent commented on account_analytic_post_by_type/__init__.py
> +# Copyright 2017 Serpent Consulting Services Pvt. Ltd.
Can you add a contributors section to the readme and put SerpentCS there and not here?

2017-09-26 09:01 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-09-26 09:50 UTC, AaronHForgeFlow approved these changes
:+1:  Thanks

2017-09-26 09:50 UTC, merged