[10.0] [ADD] account_analytic_moves_extend
Eficent/eficent-odoo-addons pull request #60
Opened 2017-09-19 09:55 UTC by nikul-serpentcs

Account Analytic Moves Extend
=============================
Limits the creation of analytic lines associated to invoices accepted only when the move is associated to an expense or revenue account.

2017-09-19 09:57 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-09-21 09:36 UTC, AaronHForgeFlow requested changes

2017-09-21 09:36 UTC, aheficent commented on account_analytic_moves_extend/model/account_move_line.py
> +                                                              'Expense'):
Expenses

2017-09-21 09:36 UTC, aheficent commented on account_analytic_moves_extend/model/account_move_line.py
> +                if obj_line.analytic_account_id:
There's no analytic journal in v10. Moreover, you are overwriting super. I think you just need to check the account user type as you are doing, and then if it's Income or expenses call super.

2017-09-25 10:15 UTC, nikul-serpentcs commented
@aheficent Could you please look it.

2017-09-26 08:24 UTC, aheficent commented on account_analytic_moves_extend/model/account_move_line.py
> +                    if obj_line.analytic_line_ids:
I think you can achieve the same result by calling super here

2017-09-26 10:45 UTC, aheficent commented on account_analytic_moves_extend/__manifest__.py
> +    "active": False,
Can you remove active here?

2017-09-26 10:53 UTC, AaronHForgeFlow approved these changes
:+1:

2017-09-26 10:53 UTC, merged